version: '3'

services:
    
  server:
    container_name: server
    build: ./server
    command: sh 'start_prod.sh'
    volumes:
      - static_volume:/app/static
      - /home/Jalyuzi/server/media:/app/media
      - db:/app/.db.sqlite3
    ports:
      - "8000:8000"
    networks:
      - main

  frontend:
    container_name: frontend
    build: ./frontend
    command: sh 'start_dev.sh'
    ports:
      - "3000:3000"
    networks:
      - main
    volumes:
      - assets_volume:/app/assets
    depends_on:
      - server

    
volumes:
  static_volume:
  media_volume:
  assets_volume:
  db:


networks:
  main:
    driver: bridge
