version: '3'

services:

  db:
    container_name: postgres_db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql/init.sql:/docker-entrypoint-initdb.d/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_PASSWORD=postgres
    networks:
      - main
    
  server:
    container_name: server
    build: ./server
    command: sh 'start_prod.sh'
    links:
      - db:db
    volumes:
      - static_volume:/app/static
      - /home/Documents/Jalyuzi/server/media:/app/media
    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - db
  
  

  frontend:
    container_name: frontend
    build: ./frontend
    command: sh 'start_dev.sh'
    ports:
      - "3000:3000"
    networks:
      - main
    volumes:
      - assets_volume:/app/assets
    depends_on:
      - server

    
volumes:
  static_volume:
  media_volume:
  assets_volume:
  postgres_data:



networks:
  main:
    driver: bridge
