version: '3'

services:
    
  server:
    container_name: server
    build: ./server
    command: sh 'start_prod.sh'
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      
    ports:
      - "8000:8000"
    networks:
      - main

  frontend:
    container_name: "frontend"
    build: ./frontend
    
    stdin_open: true
    command: sh 'start_dev.sh'
    tty: true
    ports:
      - "3000:3000"
    networks:
      - main
    depends_on:
      - server

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static/
      - media_volume:/app/media/
    networks:
      - main

    

volumes:
  static_volume:
  media_volume:


networks:
  main:
    driver: bridge