# Generated by Django 4.1.2 on 2023-01-06 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Shaxar')),
                ('state', models.CharField(max_length=122, verbose_name='Tuman')),
                ('address', models.CharField(max_length=255, verbose_name='Maxalla, Uy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='addresses')),
            ],
            options={
                'verbose_name': 'Аддрес',
                'verbose_name_plural': 'Аддресы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.CharField(max_length=255, verbose_name='Цена за продукта')),
                ('overall_price', models.CharField(max_length=255, verbose_name='Обшая цена')),
                ('size', models.CharField(max_length=100, verbose_name='Общ.кв')),
                ('type_id', models.CharField(max_length=255, verbose_name='Цвето коррекция')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('canceled', 'canceled'), ('sold', 'sold')], max_length=8, verbose_name='Статус')),
                ('amount', models.BigIntegerField(verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.address', verbose_name='Адресс')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
