# Generated by Django 4.1.2 on 2022-11-25 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_address_remove_order_client_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Аддрес', 'verbose_name_plural': 'Аддресы'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Продукт Заказ', 'verbose_name_plural': 'Продукт Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='order.orderproduct', verbose_name='Заказ'),
            preserve_default=False,
        ),
    ]
