# Generated by Django 4.1.4 on 2023-01-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_amount_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_id',
            field=models.CharField(default=None, max_length=255, verbose_name='Цвето коррекция'),
            preserve_default=False,
        ),
    ]
