# Generated by Django 4.1.2 on 2022-10-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirm',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
