# Generated by Django 4.1.2 on 2022-10-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
