# Generated by Django 4.1.4 on 2023-01-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_customuser_first_confirm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
