# Generated by Django 4.1.2 on 2023-01-07 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.CharField(max_length=255, verbose_name='Клиенты')),
                ('experience', models.CharField(max_length=255, verbose_name='Опыт работы')),
                ('products', models.CharField(max_length=255, verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Достижения',
                'verbose_name_plural': 'Достижение',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталогы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='category_images/')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Цвета',
                'verbose_name_plural': 'Цветы',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=255, verbose_name='Маил')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер')),
                ('message', models.TextField(max_length=255, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщеныя',
                'verbose_name_plural': 'Сообщеные',
            },
        ),
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип ткани',
                'verbose_name_plural': 'Тип ткани',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Свойства',
                'verbose_name_plural': 'Свойствы',
            },
        ),
        migrations.CreateModel(
            name='ValuteExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valute', models.BigIntegerField(verbose_name='Введите Узбекскую сумму')),
            ],
            options={
                'verbose_name': 'Курс Валюты',
                'verbose_name_plural': 'Курсы Валюты',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='subcategory_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category')),
            ],
            options={
                'verbose_name': 'Суб-Категории',
                'verbose_name_plural': 'Суб-Категория',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('model', models.CharField(max_length=255, verbose_name='Модел')),
                ('type_id', models.BooleanField(default=False, verbose_name='Есть ли Тип продукта*')),
                ('weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина')),
                ('blackout', models.CharField(max_length=255, verbose_name='Затемнение')),
                ('image', models.ImageField(null=True, upload_to='products')),
                ('price', models.CharField(max_length=500, verbose_name='Сумма в $')),
                ('count', models.IntegerField()),
                ('status', models.BooleanField(default=False, verbose_name='Публикация')),
                ('price_sum', models.CharField(blank=True, max_length=500, null=True, verbose_name='Цена на сум')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('image_url', models.URLField(null=True)),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.catalog', verbose_name='Каталог')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category', verbose_name='Категория')),
                ('color', models.ManyToManyField(blank=True, related_name='products', to='core.color', verbose_name='Цветы')),
                ('fabrictype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.fabrictype', verbose_name='Тип ткании')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.property', verbose_name='Свойствы')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.subcategory', verbose_name='Суб-Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
