# Generated by Django 4.1.2 on 2022-10-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
