# Generated by Django 4.1.4 on 2023-01-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='url', max_length=800),
            preserve_default=False,
        ),
    ]
