# Generated by Django 4.1.2 on 2022-12-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.CharField(max_length=255, verbose_name='Клиенты')),
                ('experience', models.CharField(max_length=255, verbose_name='Опыт работы')),
                ('products', models.CharField(max_length=255, verbose_name='Продукты')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=255, verbose_name='Маил')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер')),
                ('message', models.TextField(max_length=255, verbose_name='Сообщение')),
            ],
        ),
    ]
