# Generated by Django 4.1.2 on 2023-01-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_achievement_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuteExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valute', models.BigIntegerField(verbose_name='Введите Узбекскую сумму')),
            ],
            options={
                'verbose_name': 'Курс Валюты',
                'verbose_name_plural': 'Курсы Валюты',
            },
        ),
    ]
