# Generated by Django 4.1.2 on 2023-01-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_valuteexchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижения', 'verbose_name_plural': 'Достижение'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Сообщеныя', 'verbose_name_plural': 'Сообщеные'},
        ),
        migrations.AddField(
            model_name='product',
            name='price_sum',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=500, verbose_name='Сумма'),
        ),
    ]
