# Generated by Django 4.1.2 on 2023-01-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_achievement_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет Продукта*'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=500, verbose_name='Сумма в $'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_sum',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Цена на сум'),
        ),
    ]
