# Generated by Django 4.1.2 on 2023-01-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_color_id_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='products', to='core.color', verbose_name='Цветы'),
        ),
    ]
