# Generated by Django 4.1.4 on 2023-01-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_id',
        ),
        migrations.AddField(
            model_name='product',
            name='type_id',
            field=models.BooleanField(default=False, verbose_name='Тип продукта*'),
        ),
    ]
